version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
  
  db:
    image: vhuynh7588/pitstop-performance:v1.1
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: pitstop_performance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
